name: Clean up packages
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/delete-package-versions@v4
        with:
          package-name: "aws-source"
          package-type: "container"
          min-versions-to-keep: 90
          delete-only-untagged-versions: "true"
