---
name: depot
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - "main"
    tags:
      - "v*"
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read # required for checkout
      id-token: write # mint credentials through OIDC
      packages: write

    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: Dockerfile
            image_name: aws-source

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Cloudsmith Container Registry
        uses: docker/login-action@v3
        with:
          registry: docker.cloudsmith.io
          username: ${{ secrets.CLOUDSMITH_SERVICE_USER }}
          password: ${{ secrets.CLOUDSMITH_API_KEY }}

      - uses: depot/setup-action@v1

      - name: Build and push
        id: push
        uses: depot/build-push-action@v1
        with:
          project: xnsnw3m20t
          file: build/package/${{ matrix.dockerfile }}
          context: .
          sbom: true
          platforms: linux/amd64,linux/arm64
          push: true
          tags: docker.cloudsmith.io/overmind/service/${{ matrix.image_name }}:depot
